// import NavBar from "./components/NavBar";
import Navbar from "../pages/components/Navbar";
import AuthContext from "../context/AuthContext2";
// import "./globals.css";
// import "react-datepicker/dist/react-datepicker.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <>
      <AuthContext>
        <Navbar />
        <main>{children}</main>
      </AuthContext>
    </>
  );
};

export default RootLayout;
